version: '2'

services:
  liberty0:
    container_name: liberty0
    image: ibmcom/websphere-liberty:20.0.0.6-full-java8-ibmjava-ubi
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/dropins:/config/dropins
    - $PWD/../shared_libraries/mssql-jdbc-8.3.0.jre8-preview.jar:/config/mssql-jdbc-8.3.0.jre8-preview.jar
#    - $PWD/../key.p12:/opt/ibm/wlp/output/defaultServer/resources/security/key.p12 
    - $PWD/../shared_libraries/hazelcast-3.12.8.jar:/config/hazelcast.jar
    - $PWD/../hazelcast-config.xml:/config/hazelcast-config.xml
    - $PWD/server.xml:/config/server.xml
    - $PWD/server.env:/config/server.env
    - $PWD/bootstrap0.properties:/config/bootstrap.properties
    environment:
    - KEYSTORE_REQUIRED=false
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
    network_mode:  "host"
  liberty1:
    container_name: liberty1
    image: ibmcom/websphere-liberty:20.0.0.6-full-java8-ibmjava-ubi
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/dropins:/config/dropins
    - $PWD/../shared_libraries/mssql-jdbc-8.3.0.jre8-preview.jar:/config/mssql-jdbc-8.3.0.jre8-preview.jar
 #   - $PWD/../key.p12:/opt/ibm/wlp/output/defaultServer/resources/security/key.p12
    - $PWD/../hazelcast-3.12.8.jar:/config/hazelcast.jar
    - $PWD/../hazelcast-config.xml:/config/hazelcast-config.xml
    - $PWD/server.xml:/config/server.xml
    - $PWD/server.env:/config/server.env
    - $PWD/bootstrap1.properties:/config/bootstrap.properties
    environment:
    - KEYSTORE_REQUIRED=false
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
    network_mode:  "host"


