version: '3'

services:
  ihs:
    container_name: ihs
    image: ibmcom/ibm-http-server:9.0.5.0
    volumes:
    - $PWD/httpd.conf:/opt/IBM/HTTPServer/conf/httpd.conf
    - $PWD/../ssl/ihsserverkey.kdb:/opt/IBM/HTTPServer/conf/ihsserverkey.kdb
    - $PWD/../ssl/ihsserverkey.sth:/opt/IBM/HTTPServer/conf/ihsserverkey.sth
    - $PWD/plugin-cfg.xml:/opt/IBM/WebSphere/Plugins/config/webserver1/plugin-cfg.xml
    - $PWD/plugin-key.kdb:/opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.kdb
    - $PWD/plugin-key.sth:/opt/IBM/WebSphere/Plugins/config/webserver1/plugin-key.sth
    environment:
    - TZ=Asia/Taipei
#    network_mode:  "host"
    ports:
    - "80:80"
    - "443:443"
  redis:
    container_name: redis
    restart: always
    image: sameersbn/redis:4.0.9-3
    sysctls:
      net.core.somaxconn: '4096'
    command:
    - --loglevel warning
    volumes:
    - $PWD/liberty/redis:/var/lib/redis:Z
    environment:    
    - TZ=Asia/Taipei
    command: > 
            bash -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf
            && redis-server /etc/redis/redis.conf --appendonly yes"
    network_mode:  "host"
